name: Satellites Docker CI Ubuntu

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/renovate.json5'
      - '.github/CODEOWNERS'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/renovate.json5'
      - '.github/CODEOWNERS'
      - 'LICENSE'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-earthly:
    uses: ./.github/workflows/build-earthly.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  docker-lint:
    needs: build-earthly
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+lint-all"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-tests-quick:
    needs: build-earthly
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-misc"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
      EXTRA_ARGS: "--no-cache"
    secrets: inherit

  docker-build-with-satellites:
    needs: build-earthly
    uses: ./.github/workflows/reusable-docker-build-integrations.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit
