name: Satellites Docker CI Ubuntu

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/renovate.json5'
      - '.github/CODEOWNERS'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/renovate.json5'
      - '.github/CODEOWNERS'
      - 'LICENSE'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-earthly:
    uses: ./.github/workflows/build-earthly.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  docker-lint:
    needs: build-earthly
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+lint-all"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-tests-quick:
    needs: build-earthly
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-quick"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-tests-no-qemu-group1:
    needs: build-earthly
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group1"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-tests-no-qemu-group2:
    needs: build-earthly
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group2"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-tests-no-qemu-group3:
    needs: build-earthly
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group3"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-tests-no-qemu-group4:
    needs: build-earthly
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group4"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-tests-no-qemu-slow:
    needs: build-earthly
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-slow"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-tests-require-account-access:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    needs: build-earthly
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "./tests+tests-that-require-earthly-technologies-account-access"
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-tests-qemu:
    needs: build-earthly
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-qemu"
      USE_QEMU: true
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-satellites-examples-1:
    needs: build-earthly
    uses: ./.github/workflows/reusable-example.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      EXAMPLE_NAME: "+examples-1"
      USE_SATELLITE: true
      SATELLITE_NAME: "core-examples"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-satellites-examples-2:
    needs: build-earthly
    uses: ./.github/workflows/reusable-example.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      EXAMPLE_NAME: "+examples-2"
      USE_SATELLITE: true
      SATELLITE_NAME: "core-examples"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-satellites-examples-3:
    needs: build-earthly
    uses: ./.github/workflows/reusable-example.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      EXAMPLE_NAME: "+examples-3"
      USE_SATELLITE: true
      SATELLITE_NAME: "core-examples"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-satellites-test-local:
    needs: build-earthly
    uses: ./.github/workflows/reusable-test-local.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUN_EARTHLY_TEST_ARGS: "--no-output --use-remote-registry"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      BINARY_COMPOSE: "\"docker compose\""
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit

  docker-build-with-satellites:
    needs: build-earthly
    uses: ./.github/workflows/reusable-docker-build-integrations.yml
    with:
      BUILT_EARTHLY_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      USE_SATELLITE: true
      SATELLITE_NAME: "core-test"
      EARTHLY_ORG: "earthly-technologies"
    secrets: inherit
