name: Test on Satellites

on:
  push:
    branches: [ main ]
    paths-ignore: [ docs/** ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ docs/** ]

jobs:
  tests:
    name: +test +test-fail (satellites)
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      EARTHLY_INSTALL_ID: "earthly-githubactions"
      EARTHLY_ORG: "earthly-technologies"
    steps:
      - uses: earthly/actions-setup@v1.0.1
      - uses: actions/checkout@v3
      - name: Docker mirror login (Earthly Only)
        run: docker login registry-1.docker.io.mirror.corp.earthly.dev --username "${{ secrets.DOCKERHUB_MIRROR_USERNAME }}" --password "${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}"
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Configure Satellites (Earthly Only)
        run: earthly satellite select earthly-cloud
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Configure Earthly to use mirror (Earthly Only)
        run: |-
          earthly config global.buildkit_additional_config "'[registry.\"docker.io\"]

          mirrors = [\"registry-1.docker.io.mirror.corp.earthly.dev\"]'"
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Build latest earthly using released earthly
        run: earthly +for-linux
      - name: rebuild earthly using latest earthly build
        run: ./build/linux/amd64/earthly +for-linux
      - name: Set EARTHLY_VERSION_FLAG_OVERRIDES env
        run: |-
            set -euo pipefail
            EARTHLY_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthly_version_flag_overrides)"
            echo "EARTHLY_VERSION_FLAG_OVERRIDES=$EARTHLY_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: Enable local registry-based exporter
        run: ./build/linux/amd64/earthly config global.local_registry_host 'tcp://127.0.0.1:8371'
      - name: Execute tests (Earthly Only)
        run: |-
          ./build/linux/amd64/earthly -P --strict --no-output \
            --build-arg DOCKERHUB_AUTH=true \
            --build-arg DOCKERHUB_USER_SECRET=+secrets/earthly-technologies/dockerhub-mirror/user \
            --build-arg DOCKERHUB_TOKEN_SECRET=+secrets/earthly-technologies/dockerhub-mirror/pass \
            --build-arg DOCKERHUB_MIRROR=registry-1.docker.io.mirror.corp.earthly.dev \
          +test
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Execute fail test
        run: "! ./build/linux/amd64/earthly --no-output --strict ./tests/fail+test-fail"

  examples1:
    name: +examples1 (satellites)
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      EARTHLY_INSTALL_ID: "earthly-githubactions"
      EARTHLY_ORG: "earthly-technologies"
    steps:
      - uses: earthly/actions-setup@v1.0.1
      - uses: actions/checkout@v3
      - name: Configure Satellites (Earthly Only)
        run: earthly satellite select earthly-cloud
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Docker mirror login (Earthly Only)
        run: docker login registry-1.docker.io.mirror.corp.earthly.dev --username "${{ secrets.DOCKERHUB_MIRROR_USERNAME }}" --password "${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}"
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Configure Earthly to use mirror (Earthly Only)
        run: |-
          earthly config global.buildkit_additional_config "'[registry.\"docker.io\"]

          mirrors = [\"registry-1.docker.io.mirror.corp.earthly.dev\"]'"
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Docker Login (main build)
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_TOKEN }}"
        if: github.event_name == 'push'
      - name: Build latest earthly using released earthly
        run: earthly +for-linux
      - name: Set EARTHLY_VERSION_FLAG_OVERRIDES env
        run: |-
            set -euo pipefail
            EARTHLY_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthly_version_flag_overrides)"
            echo "EARTHLY_VERSION_FLAG_OVERRIDES=$EARTHLY_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: Enable local registry-based exporter
        run: ./build/linux/amd64/earthly config global.local_registry_host 'tcp://127.0.0.1:8371'
      - name: Build examples1 (PR build)
        run: ./build/linux/amd64/earthly -P --strict --no-output +examples1
        if: github.event_name != 'push'
      - name: Build examples1 (main build)
        run: ./build/linux/amd64/earthly -P --strict --no-output --push +examples1
        if: github.event_name == 'push'

  examples2:
    name: +examples2 (satellites)
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      EARTHLY_INSTALL_ID: "earthly-githubactions"
      EARTHLY_ORG: "earthly-technologies"
    steps:
      - uses: earthly/actions-setup@v1.0.1
      - uses: actions/checkout@v3
      - name: Configure Satellites (Earthly Only)
        run: earthly satellite select earthly-cloud
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Docker mirror login (Earthly Only)
        run: docker login registry-1.docker.io.mirror.corp.earthly.dev --username "${{ secrets.DOCKERHUB_MIRROR_USERNAME }}" --password "${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}"
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Configure Earthly to use mirror (Earthly Only)
        run: |-
          earthly config global.buildkit_additional_config "'[registry.\"docker.io\"]

          mirrors = [\"registry-1.docker.io.mirror.corp.earthly.dev\"]'"
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Docker Login (main build)
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_TOKEN }}"
        if: github.event_name == 'push'
      - name: Build latest earthly using released earthly
        run: earthly +for-linux
      - name: Set EARTHLY_VERSION_FLAG_OVERRIDES env
        run: |-
            set -euo pipefail
            EARTHLY_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthly_version_flag_overrides)"
            echo "EARTHLY_VERSION_FLAG_OVERRIDES=$EARTHLY_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: Enable local registry-based exporter
        run: ./build/linux/amd64/earthly config global.local_registry_host 'tcp://127.0.0.1:8371'
      - name: Build examples2 (PR build)
        run: ./build/linux/amd64/earthly -P --strict --no-output +examples2
        if: github.event_name != 'push'
      - name: Build examples2 (main build)
        run: ./build/linux/amd64/earthly -P --strict --no-output --push +examples2
        if: github.event_name == 'push'

  test-local:
    name: +test-local (satellites)
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      EARTHLY_INSTALL_ID: "earthly-githubactions"
    steps:
      - uses: earthly/actions-setup@v1.0.1
      - uses: actions/checkout@v3
      - name: Build latest earthly using released earthly
        run: earthly --use-inline-cache +for-linux
      - name: Configure Satellites (Earthly Only)
        run: earthly satellite select earthly-cloud
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Set EARTHLY_VERSION_FLAG_OVERRIDES env
        run: |-
            set -euo pipefail
            EARTHLY_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthly_version_flag_overrides)"
            echo "EARTHLY_VERSION_FLAG_OVERRIDES=$EARTHLY_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: Run general local tests
        run: "./build/linux/amd64/earthly --no-output ./tests/local+all"
