name: Update Docker Hub READMEs

on:
  push:
    branches: [ main ]
    paths: [ docs/docker-images/*.md ]

jobs:
  update-docker-hub-readmes:
    name: update dockerhub readmes
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update DockerHub description for earthly/earthly
        uses: peter-evans/dockerhub-description@v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: earthly/earthly
          readme-filepath: ./docs/docker-images/all-in-one.md
          short-description: ${{ github.event.repository.description }}
      - name: Update DockerHub description for earthly/buildkitd
        uses: peter-evans/dockerhub-description@v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: earthly/buildkitd
          readme-filepath: ./docs/docker-images/buildkit-standalone.md
          short-description: Standalone Earthly buildkitd image
      - name: Update DockerHub description for earthly/dind
        uses: peter-evans/dockerhub-description@v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: earthly/dind
          readme-filepath: ./docs/docker-images/dind.md
          short-description: Standalone Earthly buildkitd image
